version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@8.0.0

jobs:
  check-linting:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: Run lint
          command: |
            hadolint Dockerfile

workflows:
  default:
    jobs:
      - check-linting
      - aws-ecr/build-and-push-image:
          create-repo: true
          repo: nginx-hello-world
          tag: 'latest,$CIRCLE_WORKFLOW_ID'

          requires: [check-linting]